class CRTEncoder:
    def __init__(self, gear_teeth: int, turret_teeth: int, unit: float): ...

    def get_gear_teeth(self) -> int: ...
    def get_turret_teeth(self) -> int: ...

    def get_angle01(self) -> float: ...
    def set_angle01(self, angle: float): ...

    def get_angle(self) -> float: ...
    def set_angle(self, angle: float): ...

    def estimate_encoder_turn(self, turret_turn: float) -> float: ...

    def estimate(self, n: int) -> float: ...


class CRT:
    def __init__(self, encoder_a: CRTEncoder, encoder_b: CRTEncoder, turret_teeth: int): ...

    def max_rotation(self) -> float: ...

    def is_coprime(self) -> bool: ...
    def can_do_rotation(self, rotation_count: float) -> bool: ...
    def is_valid(self, rotation_count: float) -> bool: ...

    def get_turn(
        self,
        weight_a: float = 1.,
        weight_b: float = 1.,
        max_turn: float = float('inf'),
        previous_turn: float = float('nan'),
        proximity_weight: float = 0.
    ) -> float: ...
    def set_turn(self, turn: float): ...
